=== jluzardo1971/ActiveGanttVBW/AGVBWCON/HPM_XML/tb_GuysStThomas_Predecessors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tb_GuysStThomas_Predecessors" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tb_GuysStThomas_Predecessors">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="lID " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="ID" index-key="lID " primary="no" unique="no" clustered="no"/>
<od:index index-name="PredecessorID" index-key="lPredecessorID " primary="no" unique="no" clustered="no"/>
<od:index index-name="TaskID" index-key="lSuccessorID " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="lID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="lPredecessorID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="lSuccessorID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="yType" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="lLagFactor" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="yLagInterval" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== jluzardo1971/ActiveGanttVBW/AGVBWCON/HPM_XML/tb_GuysStThomas_Predecessors.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tb_GuysStThomas_Predecessors.xsd" generated="2012-09-27T10:43:23">
<tb_GuysStThomas_Predecessors>
<lID>49</lID>
<lPredecessorID>16</lPredecessorID>
<lSuccessorID>17</lSuccessorID>
<yType>0</yType>
<lLagFactor>696</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>50</lID>
<lPredecessorID>13</lPredecessorID>
<lSuccessorID>5</lSuccessorID>
<yType>0</yType>
<lLagFactor>516</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>51</lID>
<lPredecessorID>21</lPredecessorID>
<lSuccessorID>22</lSuccessorID>
<yType>0</yType>
<lLagFactor>-612</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>52</lID>
<lPredecessorID>24</lPredecessorID>
<lSuccessorID>19</lSuccessorID>
<yType>0</yType>
<lLagFactor>-3468</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>53</lID>
<lPredecessorID>18</lPredecessorID>
<lSuccessorID>20</lSuccessorID>
<yType>3</yType>
<lLagFactor>2316</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>54</lID>
<lPredecessorID>29</lPredecessorID>
<lSuccessorID>26</lSuccessorID>
<yType>3</yType>
<lLagFactor>1524</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>55</lID>
<lPredecessorID>27</lPredecessorID>
<lSuccessorID>32</lSuccessorID>
<yType>3</yType>
<lLagFactor>-2664</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>56</lID>
<lPredecessorID>38</lPredecessorID>
<lSuccessorID>36</lSuccessorID>
<yType>3</yType>
<lLagFactor>-3192</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>57</lID>
<lPredecessorID>12</lPredecessorID>
<lSuccessorID>14</lSuccessorID>
<yType>1</yType>
<lLagFactor>3204</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>58</lID>
<lPredecessorID>48</lPredecessorID>
<lSuccessorID>47</lSuccessorID>
<yType>1</yType>
<lLagFactor>2544</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>59</lID>
<lPredecessorID>52</lPredecessorID>
<lSuccessorID>55</lSuccessorID>
<yType>1</yType>
<lLagFactor>-1092</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>60</lID>
<lPredecessorID>56</lPredecessorID>
<lSuccessorID>53</lSuccessorID>
<yType>1</yType>
<lLagFactor>-1584</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>61</lID>
<lPredecessorID>40</lPredecessorID>
<lSuccessorID>41</lSuccessorID>
<yType>2</yType>
<lLagFactor>1656</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>62</lID>
<lPredecessorID>58</lPredecessorID>
<lSuccessorID>57</lSuccessorID>
<yType>2</yType>
<lLagFactor>1320</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>63</lID>
<lPredecessorID>62</lPredecessorID>
<lSuccessorID>63</lSuccessorID>
<yType>2</yType>
<lLagFactor>-732</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
<tb_GuysStThomas_Predecessors>
<lID>64</lID>
<lPredecessorID>67</lPredecessorID>
<lSuccessorID>65</lSuccessorID>
<yType>2</yType>
<lLagFactor>-948</lLagFactor>
<yLagInterval>2</yLagInterval>
</tb_GuysStThomas_Predecessors>
</dataroot>
