=== jluzardo1971/ActiveGanttVBW/AGVBWCON/CR_XML/tb_CR_Rows.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tb_CR_Rows" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tb_CR_Rows">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="lRowID " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="lCarID" index-key="lRowID " primary="no" unique="no" clustered="no"/>
<od:index index-name="lMKID" index-key="lCarTypeID " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="lRowID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="lDepth" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="lOrder" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="sLicensePlates" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="lCarTypeID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="sNotes" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="cRate" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="sACRISSCode" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="4"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sCity" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sBranchName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sState" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="2"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sPhone" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sManagerName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sManagerMobile" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sAddress" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sZIP" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== jluzardo1971/ActiveGanttVBW/AGVBWCON/CR_XML/tb_CR_Rows.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tb_CR_Rows.xsd" generated="2011-04-10T10:16:33">
<tb_CR_Rows>
<lRowID>28</lRowID>
<lDepth>0</lDepth>
<lOrder>1</lOrder>
<lCarTypeID>0</lCarTypeID>
<cRate>0</cRate>
<sCity>Hillsboro Beach</sCity>
<sBranchName>Hillsboro Beach</sBranchName>
<sState>FL</sState>
<sPhone>(175) 157-9697</sPhone>
<sManagerName>Nancy Mcatee</sManagerName>
<sManagerMobile>(175) 554-7615</sManagerMobile>
<sAddress>113 Bueno Drive</sAddress>
<sZIP>22454</sZIP>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>29</lRowID>
<lDepth>1</lDepth>
<lOrder>2</lOrder>
<sLicensePlates>CKT-2542</sLicensePlates>
<lCarTypeID>39</lCarTypeID>
<sNotes></sNotes>
<cRate>245</cRate>
<sACRISSCode>FFBV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>30</lRowID>
<lDepth>1</lDepth>
<lOrder>3</lOrder>
<sLicensePlates>XXW-9757</sLicensePlates>
<lCarTypeID>14</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>EDAZ</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>31</lRowID>
<lDepth>1</lDepth>
<lOrder>4</lOrder>
<sLicensePlates>HGO-6751</sLicensePlates>
<lCarTypeID>16</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>EDAZ</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>32</lRowID>
<lDepth>1</lDepth>
<lOrder>5</lOrder>
<sLicensePlates>QIZ-1491</sLicensePlates>
<lCarTypeID>17</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>ECAZ</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>33</lRowID>
<lDepth>1</lDepth>
<lOrder>6</lOrder>
<sLicensePlates>WGN-3159</sLicensePlates>
<lCarTypeID>46</lCarTypeID>
<sNotes></sNotes>
<cRate>77</cRate>
<sACRISSCode>LCAR</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>34</lRowID>
<lDepth>1</lDepth>
<lOrder>8</lOrder>
<sLicensePlates>TJS-5515</sLicensePlates>
<lCarTypeID>37</lCarTypeID>
<sNotes></sNotes>
<cRate>245</cRate>
<sACRISSCode>FFBV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>35</lRowID>
<lDepth>1</lDepth>
<lOrder>9</lOrder>
<sLicensePlates>FPN-9487</sLicensePlates>
<lCarTypeID>31</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>CDMV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>36</lRowID>
<lDepth>1</lDepth>
<lOrder>10</lOrder>
<sLicensePlates>ENU-2926</sLicensePlates>
<lCarTypeID>26</lCarTypeID>
<sNotes></sNotes>
<cRate>45</cRate>
<sACRISSCode>FWAV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>37</lRowID>
<lDepth>1</lDepth>
<lOrder>11</lOrder>
<sLicensePlates>MND-5686</sLicensePlates>
<lCarTypeID>11</lCarTypeID>
<sNotes></sNotes>
<cRate>39</cRate>
<sACRISSCode>IDAV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>38</lRowID>
<lDepth>1</lDepth>
<lOrder>12</lOrder>
<sLicensePlates>ZZY-1567</sLicensePlates>
<lCarTypeID>18</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>ECAZ</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>39</lRowID>
<lDepth>0</lDepth>
<lOrder>13</lOrder>
<lCarTypeID>0</lCarTypeID>
<cRate>0</cRate>
<sCity>Woodville</sCity>
<sBranchName>Woodville</sBranchName>
<sState>OK</sState>
<sPhone>(145) 548-2974</sPhone>
<sManagerName>Matthew Risner</sManagerName>
<sManagerMobile>(145) 679-8583</sManagerMobile>
<sAddress>8 Navarro Junction</sAddress>
<sZIP>61614</sZIP>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>40</lRowID>
<lDepth>1</lDepth>
<lOrder>14</lOrder>
<sLicensePlates>SGL-3748</sLicensePlates>
<lCarTypeID>24</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>CDAV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>41</lRowID>
<lDepth>1</lDepth>
<lOrder>15</lOrder>
<sLicensePlates>VYW-1478</sLicensePlates>
<lCarTypeID>43</lCarTypeID>
<sNotes></sNotes>
<cRate>51</cRate>
<sACRISSCode>FVAV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>42</lRowID>
<lDepth>1</lDepth>
<lOrder>16</lOrder>
<sLicensePlates>LXV-4412</sLicensePlates>
<lCarTypeID>27</lCarTypeID>
<sNotes></sNotes>
<cRate>45</cRate>
<sACRISSCode>FWAV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>44</lRowID>
<lDepth>1</lDepth>
<lOrder>7</lOrder>
<sLicensePlates>IMU-3364</sLicensePlates>
<lCarTypeID>23</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>CDAV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>45</lRowID>
<lDepth>1</lDepth>
<lOrder>17</lOrder>
<sLicensePlates>FRG-8842</sLicensePlates>
<lCarTypeID>30</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>CDMV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>46</lRowID>
<lDepth>1</lDepth>
<lOrder>18</lOrder>
<sLicensePlates>OJQ-8553</sLicensePlates>
<lCarTypeID>14</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>EDAZ</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>47</lRowID>
<lDepth>1</lDepth>
<lOrder>19</lOrder>
<sLicensePlates>INT-3737</sLicensePlates>
<lCarTypeID>5</lCarTypeID>
<sNotes></sNotes>
<cRate>223</cRate>
<sACRISSCode>PWDV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>48</lRowID>
<lDepth>1</lDepth>
<lOrder>20</lOrder>
<sLicensePlates>USM-8758</sLicensePlates>
<lCarTypeID>47</lCarTypeID>
<sNotes></sNotes>
<cRate>77</cRate>
<sACRISSCode>LCAR</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>49</lRowID>
<lDepth>1</lDepth>
<lOrder>21</lOrder>
<sLicensePlates>RRL-2724</sLicensePlates>
<lCarTypeID>32</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>CDMV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>50</lRowID>
<lDepth>1</lDepth>
<lOrder>22</lOrder>
<sLicensePlates>EMF-3865</sLicensePlates>
<lCarTypeID>20</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>CDAV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>51</lRowID>
<lDepth>1</lDepth>
<lOrder>23</lOrder>
<sLicensePlates>SRC-5911</sLicensePlates>
<lCarTypeID>32</lCarTypeID>
<sNotes></sNotes>
<cRate>37</cRate>
<sACRISSCode>CDMV</sACRISSCode>
</tb_CR_Rows>
<tb_CR_Rows>
<lRowID>52</lRowID>
<lDepth>1</lDepth>
<lOrder>24</lOrder>
<sLicensePlates>VTN-9768</sLicensePlates>
<lCarTypeID>3</lCarTypeID>
<sNotes></sNotes>
<cRate>71</cRate>
<sACRISSCode>IFBV</sACRISSCode>
</tb_CR_Rows>
</dataroot>
