=== jluzardo1971/ActiveGanttVBW/AGVBWCON/CR_XML/tb_CR_Rentals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tb_CR_Rentals" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tb_CR_Rentals">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="lTaskID " primary="yes" unique="yes" clustered="no"/>
<od:index index-name="lID" index-key="lTaskID " primary="no" unique="no" clustered="no"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="lTaskID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="lRowID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="yMode" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short"/>
<xsd:element name="sName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sAddress" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sCity" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sState" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="2"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sZIP" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sPhone" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="sMobile" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="dtPickUp" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="dtReturn" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="cRate" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="cALI" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="dCRF" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="cERF" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="cGPS" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="cLDW" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="cPAI" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="cPEP" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="cRCFC" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="cVLF" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="cWTB" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="dTax" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="cEstimatedTotal" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double"/>
<xsd:element name="bGPS" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="bFSO" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="bLDW" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="bPAI" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="bPEP" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
<xsd:element name="bALI" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== jluzardo1971/ActiveGanttVBW/AGVBWCON/CR_XML/tb_CR_Rentals.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tb_CR_Rentals.xsd" generated="2011-04-10T10:16:16">
<tb_CR_Rentals>
<lTaskID>21</lTaskID>
<lRowID>30</lRowID>
<yMode>0</yMode>
<sName>Jeromy Lapham</sName>
<sAddress>33 Mckinley Plaza</sAddress>
<sCity>Munds Park</sCity>
<sState>AZ</sState>
<sZIP>37167</sZIP>
<sPhone>(532) 463-3173</sPhone>
<sMobile>(532) 793-8291</sMobile>
<dtPickUp>2009-06-13T00:00:00</dtPickUp>
<dtReturn>2009-06-20T00:00:00</dtReturn>
<cRate>37</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>359.2151</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>22</lTaskID>
<lRowID>34</lRowID>
<yMode>0</yMode>
<sName>Colleen Nagle</sName>
<sAddress>21 Graziano Street</sAddress>
<sCity>George</sCity>
<sState>SC</sState>
<sZIP>99234</sZIP>
<sPhone>(266) 819-5725</sPhone>
<sMobile>(266) 876-2444</sMobile>
<dtPickUp>2009-06-12T00:00:00</dtPickUp>
<dtReturn>2009-06-18T12:00:00</dtReturn>
<cRate>245</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>1923.2696</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>23</lTaskID>
<lRowID>36</lRowID>
<yMode>0</yMode>
<sName>Luisa Farrior</sName>
<sAddress>86 Wiegand Courts</sAddress>
<sCity>Dayton</sCity>
<sState>VA</sState>
<sZIP>79821</sZIP>
<sPhone>(417) 727-8137</sPhone>
<sMobile>(417) 974-9449</sMobile>
<dtPickUp>2009-06-10T12:00:00</dtPickUp>
<dtReturn>2009-06-26T00:00:00</dtReturn>
<cRate>45</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>941.207</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>25</lTaskID>
<lRowID>32</lRowID>
<yMode>0</yMode>
<sName>Nancy Sandusky</sName>
<sAddress>4 Babcock Street</sAddress>
<sCity>Arlington Heights village</sCity>
<sState>IL</sState>
<sZIP>37895</sZIP>
<sPhone>(446) 926-4519</sPhone>
<sMobile>(446) 552-5686</sMobile>
<dtPickUp>2009-06-09T12:00:00</dtPickUp>
<dtReturn>2009-06-18T12:00:00</dtReturn>
<cRate>37</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>461.8481</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>26</lTaskID>
<lRowID>29</lRowID>
<yMode>0</yMode>
<sName>Shawn Kidder</sName>
<sAddress>7 Hynes Street</sAddress>
<sCity>Vernon Center</sCity>
<sState>MN</sState>
<sZIP>71625</sZIP>
<sPhone>(675) 132-8559</sPhone>
<sMobile>(675) 568-8572</sMobile>
<dtPickUp>2009-06-19T00:00:00</dtPickUp>
<dtReturn>2009-06-25T00:00:00</dtReturn>
<cRate>245</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>1847.0258</cEstimatedTotal>
<bGPS>1</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>27</lTaskID>
<lRowID>33</lRowID>
<yMode>1</yMode>
<sName>Josephina Kuo</sName>
<sAddress>7 Gruber Stravenue</sAddress>
<sCity>North Adams</sCity>
<sState>MA</sState>
<sZIP>29555</sZIP>
<sPhone>(585) 968-9925</sPhone>
<sMobile>(585) 789-1551</sMobile>
<dtPickUp>2009-06-11T12:00:00</dtPickUp>
<dtReturn>2009-06-22T12:00:00</dtReturn>
<cRate>77</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>1081.8431</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>28</lTaskID>
<lRowID>35</lRowID>
<yMode>1</yMode>
<sName>Sherie Gebhard</sName>
<sAddress>241 Booth Lock</sAddress>
<sCity>Bauxite</sCity>
<sState>AR</sState>
<sZIP>73573</sZIP>
<sPhone>(893) 882-9983</sPhone>
<sMobile>(893) 854-1831</sMobile>
<dtPickUp>2009-06-11T00:00:00</dtPickUp>
<dtReturn>2009-06-21T00:00:00</dtReturn>
<cRate>37</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>513.1645</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>29</lTaskID>
<lRowID>29</lRowID>
<yMode>0</yMode>
<sName>Linda Roscoe</sName>
<sAddress>17 Rosenberry Underpass</sAddress>
<sCity>Siler</sCity>
<sState>NC</sState>
<sZIP>23686</sZIP>
<sPhone>(929) 872-1524</sPhone>
<sMobile>(929) 546-9944</sMobile>
<dtPickUp>2009-06-11T00:00:00</dtPickUp>
<dtReturn>2009-06-17T00:00:00</dtReturn>
<cRate>245</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>1775.3258</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>30</lTaskID>
<lRowID>37</lRowID>
<yMode>0</yMode>
<sName>Matthew Alfred</sName>
<sAddress>298 Burcham Street</sAddress>
<sCity>Kivalina</sCity>
<sState>AK</sState>
<sZIP>88648</sZIP>
<sPhone>(896) 563-7588</sPhone>
<sMobile>(896) 973-8419</sMobile>
<dtPickUp>2009-06-11T12:00:00</dtPickUp>
<dtReturn>2009-06-20T12:00:00</dtReturn>
<cRate>39</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>483.0129</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>31</lTaskID>
<lRowID>31</lRowID>
<yMode>1</yMode>
<sName>Betty Ballew</sName>
<sAddress>6 Gillespie Drive</sAddress>
<sCity>Souris</sCity>
<sState>ND</sState>
<sZIP>99572</sZIP>
<sPhone>(718) 942-2143</sPhone>
<sMobile>(718) 726-7799</sMobile>
<dtPickUp>2009-06-13T00:00:00</dtPickUp>
<dtReturn>2009-06-23T12:00:00</dtReturn>
<cRate>37</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>538.8227</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>32</lTaskID>
<lRowID>40</lRowID>
<yMode>0</yMode>
<sName>Jame Josephson</sName>
<sAddress>52 Danford Circle</sAddress>
<sCity>Arkport village</sCity>
<sState>NY</sState>
<sZIP>16792</sZIP>
<sPhone>(289) 991-7674</sPhone>
<sMobile>(289) 669-9184</sMobile>
<dtPickUp>2009-06-10T12:00:00</dtPickUp>
<dtReturn>2009-06-21T00:00:00</dtReturn>
<cRate>37</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>538.8227</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>33</lTaskID>
<lRowID>42</lRowID>
<yMode>0</yMode>
<sName>Penny Holsinger</sName>
<sAddress>1 Mariano Fields</sAddress>
<sCity>Seneca Knolls</sCity>
<sState>NY</sState>
<sZIP>58312</sZIP>
<sPhone>(372) 274-7459</sPhone>
<sMobile>(372) 576-9947</sMobile>
<dtPickUp>2009-06-09T12:00:00</dtPickUp>
<dtReturn>2009-06-17T00:00:00</dtReturn>
<cRate>45</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>455.4228</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>34</lTaskID>
<lRowID>44</lRowID>
<yMode>0</yMode>
<sName>Linda Gabaldon</sName>
<sAddress>4 Lewellen Boulevard</sAddress>
<sCity>Cypress Lake</sCity>
<sState>FL</sState>
<sZIP>71862</sZIP>
<sPhone>(626) 786-3444</sPhone>
<sMobile>(626) 591-2811</sMobile>
<dtPickUp>2009-06-10T00:00:00</dtPickUp>
<dtReturn>2009-06-25T12:00:00</dtReturn>
<cRate>37</cRate>
<cALI>14.43</cALI>
<dCRF>0.0989</dCRF>
<cERF>0.67</cERF>
<cGPS>11.95</cGPS>
<cLDW>26.99</cLDW>
<cPAI>4</cPAI>
<cPEP>2.95</cPEP>
<cRCFC>4</cRCFC>
<cVLF>0.6</cVLF>
<cWTB>2.03</cWTB>
<dTax>0.07</dTax>
<cEstimatedTotal>795.405</cEstimatedTotal>
<bGPS>0</bGPS>
<bFSO>0</bFSO>
<bLDW>0</bLDW>
<bPAI>0</bPAI>
<bPEP>0</bPEP>
<bALI>0</bALI>
</tb_CR_Rentals>
<tb_CR_Rentals>
<lTaskID>35</lTaskID>
<lRowID>46</lRowID>
<yMode>0</yMode>
<sName>Gale Cottingham</sName>
<sAddress>717 Seaton Way</sAddress>
<sCity>Worthington borough</sCity>
<sState>PA</sState>
<sZIP>91136</sZIP>
<sPhone>(799) 683-3813</sPhone>
<sMobile>(799) 827-3616</sMobile>
<dtPickUp>2009-06-11T00:00:00</dtPickUp>
